# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version "2.106.0"

default_platform(:ios)

platform :ios do
  desc "Frollo SDK testing and deployment"

  lane :test do
    begin
      #setup_jenkins

      rome(
        command: "download",
        verbose: false
      )

      rome_list = rome(
        command: "list",
        missing: true,
        verbose: false
      )

      missing_list = rome_list.split("\n")
      missing_list.map! { |s| s.split(' ').first }

      carthage(
          command: "bootstrap",
          cache_builds: true,
          platform: "all",
          use_binaries: false
      )

      rome(
        command: "upload",
        frameworks: missing_list,
        verbose: false
      )

      # if carthage_cache_exist(bucket: 'frollo-carthage-cache')
      #   carthage_cache_install(
      #     bucket: 'frollo-carthage-cache'
      #   )
      # else
      #   carthage(
      #   	command: "bootstrap",
      #     platform: "all",
      #     use_binaries: false
      #   )

      #   carthage_cache_publish(
      #     bucket: 'frollo-carthage-cache'
      #   )
      # end

      xcodebuild(scheme: "FrolloSDK",
          clean: true,
          build: true,
          destination: "platform=watchOS Simulator,name=Apple Watch Series 4 - 44mm")

   	  run_tests(scheme: "FrolloSDK macOS Tests",
      		  clean: true,
      		  code_coverage: true,
      		  destination: "platform=macOS,arch=x86_64",
      		  output_directory: "fastlane/mac_test_output",
      		  slack_message: "Frollo SDK: macOS Tests")

   	  run_tests(scheme: "FrolloSDK tvOS Tests",
      		  clean: true,
      		  code_coverage: true,
      		  devices: ["Apple TV 4K"],
      		  slack_message: "Frollo SDK: tvOS Tests")

      run_tests(scheme: "FrolloSDK iOS Tests",
      		  clean: true,
      		  code_coverage: true,
      		  devices: ["iPhone 5s (10.3.1)", "iPhone X"],
      		  slack_message: "Frollo SDK: iOS Tests",
            output_style: "raw")

      xcov(project: "FrolloSDK.xcodeproj",
      	 scheme: "FrolloSDK")

      jazzy(config: ".jazzy.json")

      slack(message: "Frollo Swift SDK Successfully Integrated!",
            success: true)

    rescue => exception
      on_error(exception)
    end
  end
end

def on_error(exception)
       slack(
           message: "Frollo Swift SDK integration failed with exception : #{exception}",
           success: false,
       )
end
