# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version "2.98.0"

default_platform(:ios)

platform :ios do
  desc "Frollo SDK testing and deployment"

  lane :test do
    setup_jenkins

    if carthage_cache_exist(bucket: 'frollo-sdk-carthage-cache')
      carthage_cache_install(
        bucket: 'frollo-sdk-carthage-cache'
      )
    else
      carthage(
      	command: "bootstrap",
        platform: "all",
        use_binaries: false
      )

      carthage_cache_publish(
        bucket: 'frollo-sdk-carthage-cache'
      )
    end

 	run_tests(scheme: "FrolloSDK",
    		  clean: true,
    		  code_coverage: true,
    		  destination: "platform=macOS,arch=x86_64",
    		  output_directory: "fastlane/mac_test_output")

    run_tests(scheme: "FrolloSDK",
    		  clean: true,
    		  code_coverage: true,
    		  devices: ["iPhone 5s (10.3.1)", "iPhone X", "Apple TV 4K"])

    xcov(project: "FrolloSDK.xcodeproj",
    	 scheme: "FrolloSDK")

    jazzy

  end
end
